SELECT * FROM PAIS ORDER BY NOME DESC 
SELECT LOGRADOURO, CEP FROM ENDERECO WHERE LOGRADOURO LIKE 'A%' OR LOGRADOURO LIKE 'a%'
SELECT * FROM ENDERECO WHERE CEP LIKE '%0'
SELECT * FROM ENDERECO WHERE NUMERO BETWEEN 1 AND 100
SELECT * FROM ENDERECO WHERE LOGRADOURO LIKE UPPER('RUA%') ORDER BY CEP DESC
SELECT COUNT(id_endereco) FROM ENDERECO
SELECT ID_CIDADE, COUNT(ID_ENDERECO) FROM ENDERECO GROUP BY ID_CIDADE